// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BatteryService.Domain.Models;

public partial class BatteryHealthLog
{
    public Guid LogId { get; set; }

    public Guid BatteryId { get; set; }

    public decimal SohPercentage { get; set; }

    public int ChargeCycles { get; set; }

    public decimal? VoltageReading { get; set; }

    public decimal? TemperatureCelsius { get; set; }

    public string Notes { get; set; }

    public Guid? RecordedBy { get; set; }

    public DateTime RecordedAt { get; set; }

    public virtual Battery Battery { get; set; }
}