// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BatteryService.Domain.Models;

public partial class ev_battery_swapContext : DbContext
{
    public ev_battery_swapContext(DbContextOptions<ev_battery_swapContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Battery> Batteries { get; set; }

    public virtual DbSet<BatteryHealthLog> BatteryHealthLogs { get; set; }

    public virtual DbSet<BatteryType> BatteryTypes { get; set; }

    public virtual DbSet<Staff> Staff { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Battery>(entity =>
        {
            entity.HasKey(e => e.BatteryId).HasName("pk_batteries");

            entity.ToTable("batteries");

            entity.HasIndex(e => e.BatteryTypeId, "ix_batteries_battery_type");

            entity.HasIndex(e => e.ChargeLevel, "ix_batteries_charge_level");

            entity.HasIndex(e => e.SohPercentage, "ix_batteries_soh");

            entity.HasIndex(e => e.StationId, "ix_batteries_station");

            entity.HasIndex(e => e.Status, "ix_batteries_status");

            entity.HasIndex(e => e.BatteryCode, "ux_batteries_code").IsUnique();

            entity.HasIndex(e => e.SerialNumber, "ux_batteries_serial").IsUnique();

            entity.Property(e => e.BatteryId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("battery_id");
            entity.Property(e => e.BatteryCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("battery_code");
            entity.Property(e => e.BatteryTypeId).HasColumnName("battery_type_id");
            entity.Property(e => e.ChargeLevel).HasColumnName("charge_level");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.LastMaintenanceDate).HasColumnName("last_maintenance_date");
            entity.Property(e => e.LastSwapDate).HasColumnName("last_swap_date");
            entity.Property(e => e.ManufactureDate).HasColumnName("manufacture_date");
            entity.Property(e => e.NextMaintenanceDate).HasColumnName("next_maintenance_date");
            entity.Property(e => e.PurchaseDate).HasColumnName("purchase_date");
            entity.Property(e => e.SerialNumber)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("serial_number");
            entity.Property(e => e.SohPercentage)
                .HasDefaultValue(100.00m)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("soh_percentage");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("available")
                .HasColumnName("status");
            entity.Property(e => e.TotalCycles).HasColumnName("total_cycles");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.BatteryType).WithMany(p => p.Batteries)
                .HasForeignKey(d => d.BatteryTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_batteries_battery_types");
        });

        modelBuilder.Entity<BatteryHealthLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("pk_battery_health_logs");

            entity.ToTable("battery_health_logs");

            entity.HasIndex(e => e.BatteryId, "ix_bhl_battery");

            entity.HasIndex(e => e.RecordedAt, "ix_bhl_recorded_at");

            entity.Property(e => e.LogId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("log_id");
            entity.Property(e => e.BatteryId).HasColumnName("battery_id");
            entity.Property(e => e.ChargeCycles).HasColumnName("charge_cycles");
            entity.Property(e => e.Notes).HasColumnName("notes");
            entity.Property(e => e.RecordedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("recorded_at");
            entity.Property(e => e.RecordedBy).HasColumnName("recorded_by");
            entity.Property(e => e.SohPercentage)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("soh_percentage");
            entity.Property(e => e.TemperatureCelsius)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("temperature_celsius");
            entity.Property(e => e.VoltageReading)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("voltage_reading");

            entity.HasOne(d => d.Battery).WithMany(p => p.BatteryHealthLogs)
                .HasForeignKey(d => d.BatteryId)
                .HasConstraintName("fk_bhl_batteries");
        });

        modelBuilder.Entity<BatteryType>(entity =>
        {
            entity.HasKey(e => e.BatteryTypeId).HasName("pk_battery_types");

            entity.ToTable("battery_types");

            entity.HasIndex(e => e.TypeCode, "ux_battery_types_code").IsUnique();

            entity.Property(e => e.BatteryTypeId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("battery_type_id");
            entity.Property(e => e.CapacityKwh)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("capacity_kwh");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(sysutcdatetime())")
                .HasColumnName("created_at");
            entity.Property(e => e.Dimensions)
                .HasMaxLength(100)
                .HasColumnName("dimensions");
            entity.Property(e => e.Manufacturer)
                .HasMaxLength(100)
                .HasColumnName("manufacturer");
            entity.Property(e => e.TypeCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type_code");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("type_name");
            entity.Property(e => e.Voltage)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("voltage");
            entity.Property(e => e.WarrantyCycles).HasColumnName("warranty_cycles");
            entity.Property(e => e.WeightKg)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("weight_kg");
        });

        modelBuilder.Entity<Staff>(entity =>
        {
            entity.HasKey(e => e.StaffId).HasName("pk_staff");

            entity.ToTable("staff");

            entity.HasIndex(e => e.UserId, "UQ__staff__B9BE370E968F8940").IsUnique();

            entity.HasIndex(e => e.StationId, "ix_staff_station");

            entity.HasIndex(e => e.EmployeeCode, "ux_staff_employee_code").IsUnique();

            entity.Property(e => e.StaffId)
                .HasDefaultValueSql("(newid())")
                .HasColumnName("staff_id");
            entity.Property(e => e.EmployeeCode)
                .HasMaxLength(50)
                .HasColumnName("employee_code");
            entity.Property(e => e.HireDate).HasColumnName("hire_date");
            entity.Property(e => e.Position)
                .HasMaxLength(100)
                .HasColumnName("position");
            entity.Property(e => e.StationId).HasColumnName("station_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}